import type { BlogPostContent } from "@/content/blog-post";

/**
 * Verbatim from docs/seo-content/08 Blog/01 Posts/03 - Dental Emergencies What to Do First.docx (6 Oct 2026).
 * Generated by a one-time converter (scratchpad gen_blog.py): headings use "&" (client rule),
 * US spelling, and internal links added on the phrases the doc points at. The doc's optional
 * in-body photo slot is left out (practice-supplied photo only; no stock or AI imagery).
 */
export const dentalEmergenciesFirst: BlogPostContent = {
  "slug": "dental-emergencies-what-to-do-first",
  "meta": {
    "path": "/blog/dental-emergencies-what-to-do-first/",
    "title": "Dental Emergencies: What Counts and What to Do First",
    "description": "Toothache, swelling or a knocked-out tooth? What counts as a dental emergency, what to do first, and how to get same-day care in Bensalem, PA."
  },
  "label": "Dental Emergencies: What to Do First",
  "topic": "dental-emergencies-title",
  "art": "emergency",
  "title": {
    "lead": "Dental Emergencies:",
    "accent": "What Counts & What to Do First"
  },
  "author": "Dr. Keyur Dudhat, DMD",
  "published": "2026-10-06",
  "updated": "2026-10-06",
  "quickAnswer": {
    "text": [
      "A dental emergency is any mouth problem causing severe pain, swelling, bleeding that won't stop, or a knocked-out or broken tooth. Call or text Amazing Smiles By Design in Bensalem at (215) 639-5331 right away, and we'll arrange same-day care whenever possible. If you have severe facial swelling, trouble breathing or swallowing, or bleeding that won't stop, call 911 or go to the nearest emergency room.",
      "Lost a tooth, broken a tooth, or in bad pain? Call or text now, then see the first-aid steps below."
    ],
    "buttons": [
      {
        "label": "Call or Text (215) 639-5331",
        "href": "tel:+12156395331"
      },
      {
        "label": "Request an Emergency Visit",
        "href": "/patient-information/emergency-scheduling/"
      }
    ]
  },
  "takeaways": [
    "A dental emergency usually means severe pain, swelling, uncontrolled bleeding, or a knocked-out or broken tooth.",
    "Call or text a dentist right away; same-day care is arranged whenever possible.",
    "For a knocked-out tooth, keep it moist in milk or saliva and get seen as fast as you can.",
    "Severe facial swelling, trouble breathing or swallowing, or bleeding that won't stop is a 911 or ER situation.",
    "You don't need to be an existing patient; new patients can get a $59 emergency exam with X-rays."
  ],
  "sections": [
    {
      "id": "what-is-a-dental-emergency-title",
      "title": "What Is a Dental Emergency?",
      "blocks": [
        {
          "kind": "p",
          "text": "A [dental emergency](/general-dentistry/emergency-dentistry/) is any problem in your mouth that needs urgent care to stop pain, save a tooth, or prevent an infection from spreading. Some problems need to be seen the same day; others can wait a day or two. Here's a quick guide."
        },
        {
          "kind": "table",
          "head": [
            "See a dentist urgently",
            "Usually can wait a day or two"
          ],
          "rows": [
            [
              "Knocked-out or loose adult tooth",
              "Dull ache with no swelling"
            ],
            [
              "Severe or worsening toothache",
              "A small chip with no pain"
            ],
            [
              "Facial or gum swelling",
              "Lost filling with no pain"
            ],
            [
              "Bleeding that won't stop",
              "Mild sensitivity to hot or cold"
            ],
            [
              "Broken tooth with sharp pain",
              "Food stuck between teeth"
            ]
          ]
        },
        {
          "kind": "p",
          "text": "When you're not sure, call or text us. You don't have to diagnose it yourself; our team will tell you how quickly you should be seen."
        },
        {
          "kind": "p",
          "text": "Also treat as urgent: signs of infection or an abscess (a bad taste, or a pimple on the gum), a lost filling or crown that leaves a painful tooth, and any injury to the mouth from a fall or impact."
        }
      ]
    },
    {
      "id": "what-to-do-first-by-situation-title",
      "title": "What to Do First, by Situation",
      "blocks": [
        {
          "kind": "h3",
          "title": "A knocked-out adult tooth",
          "blocks": [
            {
              "kind": "p",
              "text": "Act fast, and handle the tooth by the crown, never the root. Based on Mayo Clinic's first-aid guidance:"
            },
            {
              "kind": "ol",
              "items": [
                "Pick it up by the crown (the chewing part), not the root.",
                "If it's dirty, rinse it gently with milk or your own saliva. Don't scrub it or use tap water.",
                "Try to place it back in the socket and bite gently on gauze to hold it.",
                "If it won't go back, keep it in a cup of milk or saliva.",
                "Get to a dentist as quickly as possible; the sooner it's replanted, the better the chance of saving it."
              ]
            },
            {
              "kind": "p",
              "text": "A baby tooth is not put back. If you're unsure whether it's a baby tooth, bring it with you."
            }
          ]
        },
        {
          "kind": "h3",
          "title": "A broken or chipped tooth",
          "blocks": [
            {
              "kind": "p",
              "text": "Rinse your mouth with warm water and save any pieces. Use a cold compress on the outside of your cheek for swelling. Call or text us so we can see how soon you need to be in."
            }
          ]
        },
        {
          "kind": "h3",
          "title": "A bad toothache or a suspected abscess",
          "blocks": [
            {
              "kind": "p",
              "text": "Rinse with warm water and floss gently to clear any trapped food. A toothache that is severe, or comes with swelling or a bad taste, can be a sign of infection that gets worse quickly, so don't wait it out. Treatment may involve a [root canal](/restorative-dentistry/non-surgical-root-canal/) to save the tooth, or a [tooth extraction](/general-dentistry/tooth-extraction/) if it can't be saved."
            }
          ]
        },
        {
          "kind": "h3",
          "title": "A lost filling or crown",
          "blocks": [
            {
              "kind": "p",
              "text": "Keep the crown if you have it. Avoid chewing on that side and call or text us to arrange a repair before the tooth is damaged further."
            }
          ]
        }
      ]
    },
    {
      "id": "when-is-it-a-911-or-er-emergency-title",
      "title": "When Is It a 911 or ER Emergency?",
      "blocks": [
        {
          "kind": "p",
          "text": "Some situations are beyond a dental office. Call 911 or go to the nearest emergency room if you have:"
        },
        {
          "kind": "ul",
          "items": [
            "Severe facial swelling, especially if it affects your eye or neck",
            "Trouble breathing or swallowing",
            "Bleeding that won't stop",
            "A serious injury to the jaw or head"
          ]
        },
        {
          "kind": "p",
          "text": "For everything else, a dentist is the right first call."
        }
      ]
    },
    {
      "id": "how-fast-can-i-be-seen-in-bensalem-title",
      "title": "How Fast Can I Be Seen in Bensalem?",
      "blocks": [
        {
          "kind": "p",
          "text": "Call or text Amazing Smiles By Design at (215) 639-5331. Our team will ask what's going on, tell you how soon you should be seen, and arrange a same-day visit whenever possible. A few things that help:"
        },
        {
          "kind": "ul",
          "items": [
            "**You don't need to be an existing patient.** New patients are welcome for emergencies.",
            "**$59 new-patient emergency visit**, which includes the exam and the necessary X-rays.",
            "**No insurance?** Our [membership plans](/specials/) include an emergency exam, and [financing](/patient-information/financing-options/) is available through CareCredit and Cherry."
          ]
        },
        {
          "kind": "cta",
          "buttons": [
            {
              "label": "Call or Text (215) 639-5331",
              "href": "tel:+12156395331"
            },
            {
              "label": "Request an Emergency Visit",
              "href": "/patient-information/emergency-scheduling/"
            }
          ]
        },
        {
          "kind": "p",
          "text": "Office hours: Monday 8 am–6 pm, Tuesday 8 am–5 pm, Wednesday 8 am–6 pm, Thursday 8 am–2 pm. Closed Friday to Sunday."
        }
      ]
    },
    {
      "id": "what-if-it-happens-when-we-re-closed-title",
      "title": "What If It Happens When We're Closed?",
      "blocks": [
        {
          "kind": "p",
          "text": "If you have severe facial swelling, trouble breathing or swallowing, or bleeding that won't stop, call 911 or go to the nearest emergency room, any time. For other problems outside our hours, call or text (215) 639-5331 and we'll help you as soon as we're open, and tell you how to stay comfortable until then."
        }
      ]
    }
  ],
  "faqs": {
    "id": "dental-emergency-faqs-title",
    "title": "Dental Emergency FAQs",
    "items": [
      {
        "question": "What is considered a dental emergency?",
        "answer": "A dental emergency is any mouth problem that needs urgent care, such as a knocked-out or broken tooth, a severe toothache, facial or gum swelling, signs of infection, or bleeding that won't stop. If severe swelling affects your breathing or swallowing, treat it as a medical emergency and call 911."
      },
      {
        "question": "Can I get a same-day emergency dental appointment in Bensalem?",
        "answer": "Yes, whenever possible. Call or text Amazing Smiles By Design at (215) 639-5331 and our team will tell you how soon you should be seen and arrange a same-day visit whenever possible. You do not need to be an existing patient to be seen for an emergency."
      },
      {
        "question": "What should I do with a knocked-out tooth?",
        "answer": "Pick the tooth up by the crown, not the root, and rinse it gently with milk or saliva if it's dirty. Try to place it back in the socket, or keep it in a cup of milk, and get to a dentist as fast as you can. The sooner it is replanted, the better the chance of saving it."
      },
      {
        "question": "How much is an emergency dental visit without insurance?",
        "answer": "New patients can have a $59 emergency visit at Amazing Smiles By Design, which includes the exam and the necessary X-rays. Membership plans also include an emergency exam, and financing is available through CareCredit and Cherry if further treatment is needed."
      },
      {
        "question": "Should I go to the ER for a toothache?",
        "answer": "For a toothache alone, a dentist is the right first call, not the ER, because a hospital usually can't treat the tooth itself. Go to the ER or call 911 if you have severe facial swelling, trouble breathing or swallowing, or bleeding that won't stop."
      }
    ]
  },
  "finalCta": {
    "id": "in-pain-call-or-text-215-639-5331-title",
    "title": {
      "lead": "In Pain?",
      "accent": "Call or Text (215) 639-5331"
    },
    "body": "Our team will tell you how soon you should be seen and arrange same-day care whenever possible. Amazing Smiles By Design, 3101 Bristol Road, Suite 1, Bensalem, PA 19020.",
    "buttons": [
      {
        "label": "Call or Text (215) 639-5331",
        "href": "tel:+12156395331"
      },
      {
        "label": "Request an Emergency Visit",
        "href": "/patient-information/emergency-scheduling/"
      }
    ]
  },
  "related": {
    "label": "Emergency dentistry",
    "href": "/general-dentistry/emergency-dentistry/"
  }
};
